### ISSUE TITLE
OAuth request failed

### ISSUE THREAD

**Issue by sulliwane** [hokiebrian/spotify_plus#3]
**Describe the bug**
When adding my credentials, it fails with below error message:

**Screenshots**
![Screenshot from 2024-08-13 09-51-28](https://github.com/user-attachments/assets/b50e4a4a-0764-403b-80fb-cce66f1d2f89)

**Environment details:**
 - Home Assistant version installed: 2024.08.1
 - Component version installed: v1.0.48
 - Spotify Account Type: Family

**Output of HA logs**
![Screenshot from 2024-08-13 09-50-41](https://github.com/user-attachments/assets/9013cf9c-4db5-466b-b928-06fefd40c35b)
![Screenshot from 2024-08-13 09-50-31](https://github.com/user-attachments/assets/b89717ff-9d6a-4344-b8ec-7dd7a959fd77)

But the authorization code is valid. Just tried creating a new one:
![image](https://github.com/user-attachments/assets/bec0c1a9-9232-43d2-a512-4574a61eff8e)

Same error: `OAuth request failed while processing SpotifyPlus OAuth Application Credentials; please check the System Log for further information`

Thanks for the help!

**Comment by collateral87** [comment]
Same issue since yesterday

**Comment by hokiebrian** [comment]
There is an issue with the Spotify API. https://community.spotify.com/t5/Spotify-for-Developers/v1-me-following-getting-403s-all-of-a-sudden/td-p/6252827

I'm seeing if there is a workaround, but not having much luck.

**Comment by hokiebrian** [comment]
The issue with the Spotify API appears to have been resolved.

**Comment by sulliwane** [comment]
![Screenshot from 2024-08-16 19-14-34](https://github.com/user-attachments/assets/1c0d979f-9882-418e-aa94-ba4aefd06aa9)
![Screenshot from 2024-08-16 19-15-06](https://github.com/user-attachments/assets/6fdec9f7-99f5-445d-b05f-651b5f41cf32)
Still have the issue today
